### PR TITLE
Fix a couple of edge case

### PR DESCRIPTION
**Pull request by gkrnours**
Hello,

I found a couple of issue with your app while working with it, so here is a pull request.

I might also work on enhancement in the near future. Things like syncing plan between local database and stripe, support for specifying the quantity in a subscription and multi plan subscription.

I would be happy to discuss how to implement all that. Else, you might see another pull request :)

### CODE REVIEW

**Comment by jacoor** [comment]
Hello @gkrnours 
Thanks for pull requests.
Would you mind fixing tests? pylint is complaining about incorrectly sorted imports.
The command is `sh run_isort.sh` with py3.6 and isort==4.2.15.

Thanks

**Comment by jacoor** [comment]
@gkrnours thanks for the PRs,
yes, we will be interested and grateful in any enhancements.

Glad you found it useful!

**Comment by jacoor** [comment]
For syncing the plans between lib and stripe I suggest using webhooks, similar to what we have done for coupons. Please check: 
https://github.com/ArabellaTech/aa-stripe/blob/master/aa_stripe/models.py#L503

For the quantity and multiple plans subscriptions, I don't have any suggestions yet. Our use case was simpler. However, it would be good to have it implemented as long as it will be backward compatible.

**Comment by gkrnours** [comment]
No problem about fixing the test but I might not do it before monday.

Thanks for the pointer on the webhooks

**Pull request merged**
